### PR TITLE
feat: add scripts to generate components from svg

### LINKED ISSUE #4: Add icons for the Kubernetes ecosystem
The community icons for [Kubernetes](https://kubernetes.io) can be found in [this repository](https://github.com/kubernetes/community/tree/master/icons/svg). We need icons for:

- [ ] Kubernetes
- [ ] Node
- [ ] Pod
- [ ] Service

### LINKED ISSUE #5: Support plain SVG as source of icons
For now, the SVG content is baked into a React component, which is not ideal to easily add new icons as some code needs to be added at different places. Looking around, https://github.com/tailwindlabs/heroicons is using script that take the SVG content and create React and Vue components. Their approach has been copied by other (under MIT license). We should do that also.

On top of the move, we need also to support the current preview (with icons download) as deployed on https://icons.datalayer.design (implemented by [IconsGallery](https://github.com/datalayer/icons/blob/main/src/IconsGallery.tsx)). We can evolve that preview page to something nicer like https://heroicons.com.

The icons will be published under `@datalayer-icons/react` and `@datalayer-icons/vue` npm packages.

### PR DESCRIPTION
**Pull request by im-adithya**
Adds script to generate react and vue components from SVG icons.
Also replaces the previously used hardcoded react icons in the vite application.

Fixes #5
Fixes #4

### CODE REVIEW

**Comment by im-adithya** [comment]
Also Fixes #4

⚠️ Missing Services Logo

**Comment by echarles** [comment]
Thx @im-adithya, this builds and works fine for me. A few feedbacks:

- You have committed in react/icons and vue/icons some javascript files which should normally be generated; Can you remove those and add in .gitignore the needed exclusions?
- How to generate icons with different size?
- I don't see the concept/structure of outline vs solid like [here](https://github.com/tailwindlabs/heroicons/tree/master/src/24). Not sure if this is need to have that right now, but better to think about that for the future.
- Can you update the README with instructions for build and use. Also instructions on how to add an icon, as how to style them.
- Can you add in the LICENSE file mention of the heroicons source usage

**Comment by echarles** [comment]
Also the package names should be `@datalayer-icons/react` and `@datalayer-icons/vue` (have not checked the others)

**Comment by im-adithya** [comment]
> You have committed in react/icons and vue/icons some javascript files which should normally be generated; Can you remove those and add in .gitignore the needed exclusions?

> Also the package names should be @datalayer-icons/react and @datalayer-icons/vue (have not checked the others)

✅ Done
> How to generate icons with different size?

We have to use TailwindCSS to size them, like in the vite application
> I don't see the concept/structure of outline vs solid like [here](https://github.com/tailwindlabs/heroicons/tree/master/src/24). Not sure if this is need to have that right now, but better to think about that for the future.

✅ Done, made outline and solid folders; initially thought of it to be unnecessary but feels like it's good to separate in the long run
> Can you update the README with instructions for build and use. Also instructions on how to add an icon, as how to style them.

✅ Done
> Can you add in the LICENSE file mention of the heroicons source usage

✅ Done

**Review by echarles — APPROVED** [review]
LGTM Thx @im-adithya.

**Pull request merged**
